"""
Django settings for uwitter project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e#_sxu&c2a*gxako!fejf5_1qxjgs4n+$4jj$_qpus^sbrthh&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'frontend'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'uwitter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uwitter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Pacific/Auckland'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = 'frontend.user_views.user_uweet_redirect'

AUTHENTICATION_BACKENDS = ('frontend.auth_backends.MicroServicesSocketBackend',)

# use frontend.auth_backends.MicroServicesBackend for HTTP REST micro-service @ MICRO_SERVICES_AUTH_URL
# or frontend.auth_backends.MicroServicesQueueBackend for queued login

MESSAGE_SERVICE = 'local'
# can also be 'local' for local DB, or 'remote' for HTTP REST micro-service @ MICRO_SERVICES_MESSAGES_URL

MICRO_SERVICES_AUTH_URL = 'http://127.0.0.1:5000'
MICRO_SERVICES_MESSAGES_URL = 'http://127.0.0.1:5001'

MICRO_SERVICES_AUTH_SOCKET = ('127.0.0.1', 5002)

NOTIFY_QUEUE_NAME = 'uwitter_notify'

QUERY_QUEUE_NAME = 'uwitter_messages_query'
RESPONSE_QUEUE_NAME = 'uwittter_messages_response'

AUTH_REQUEST_QUEUE_NAME = 'uwitter_auth_request'
AUTH_RESPONSE_QUEUE_NAME = 'uwitter_auth_response'

NOTIFIER_SERVICE = 'udp'
NOTIFIER_SERVICE_SOCKET = ('127.0.0.1', 5004)
